# Generated by Django 3.2.7 on 2022-01-06 07:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jalgale', '0001_initial'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Sitesetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images')),
                ('facebook_url', models.CharField(max_length=100)),
                ('twitter_url', models.CharField(max_length=100)),
                ('instagram_url', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('company_brief', models.CharField(max_length=100)),
                ('google_map', models.TextField()),
            ],
        ),
    ]
