# Generated by Django 3.2.7 on 2021-12-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jalgale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
