# Generated by Django 3.2.7 on 2021-12-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jalgale', '0002_project_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('messages', models.TextField()),
            ],
        ),
    ]
