# Generated by Django 3.2.7 on 2022-01-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jalgale', '0003_contact_us_content_descriptions_menu_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('messages', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='contact_us',
        ),
    ]
