# Generated by Django 3.2.7 on 2022-01-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jalgale', '0004_auto_20220104_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='messages',
            new_name='message',
        ),
    ]
